ALTER TABLE games
  ADD COLUMN white_status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  ADD COLUMN black_status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  ADD COLUMN red_status   VARCHAR(32) NOT NULL DEFAULT 'ACTIVE';
