spring.application.name=gateway-service
server.port=8080
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true
backend.base-url=${BACKEND_BASE_URL:http://localhost:8081}
frontend.base-url=${FRONTEND_BASE_URL:http://localhost:5173}